# Generated by Django 2.2.11 on 2020-03-18 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GTRCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('percentage', models.IntegerField(blank=True, default=0, null=True)),
                ('isHECategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GtR Category',
                'verbose_name_plural': 'GtR Categories',
            },
        ),
        migrations.CreateModel(
            name='HECategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_terms', models.TextField(blank=True, default='', help_text="These comma separated terms will searched for in projects. You don't need to add the Name", null=True)),
            ],
            options={
                'verbose_name': 'HE Category',
                'verbose_name_plural': 'HE Categories',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('otherNames', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('orchidID', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('href', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abstractText', models.TextField(blank=True, default=None, null=True)),
                ('start', models.DateField(blank=True, default=None, null=True)),
                ('end', models.DateField(blank=True, default=None, null=True)),
                ('created', models.DateField(blank=True, default=None, null=True)),
                ('updated', models.DateField(blank=True, default=None, null=True)),
                ('projectCategory', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('leadFunder', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('awardPounds', models.IntegerField(blank=True, default=0, null=True)),
                ('expenditurePounds', models.IntegerField(blank=True, default=0, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('GTRProjectUrl', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fundingOrgId', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gtrs', models.ManyToManyField(to='rap.GTRCategory')),
                ('leadOrganisation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap.Organisation')),
                ('pi', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap.Person')),
            ],
        ),
        migrations.CreateModel(
            name='HEResearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gtrs', models.ManyToManyField(blank=True, default=None, null=True, to='rap.GTRCategory')),
                ('hecategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rap.HECategory')),
            ],
            options={
                'verbose_name': 'HE Research Area',
                'verbose_name_plural': 'HE Research Areas',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField(default=datetime.datetime.now)),
                ('n_comments', models.IntegerField(blank=True, null=True)),
                ('n_pingbacks', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='rap.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rap.Blog')),
            ],
        ),
    ]
