# Generated by Django 2.2.11 on 2020-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hecategory',
            name='search_terms',
        ),
        migrations.AddField(
            model_name='heresearcharea',
            name='search_terms',
            field=models.TextField(blank=True, default='', help_text="One per line. Terms will searched for in projects. You don't need to add the name of this category", null=True),
        ),
        migrations.AlterField(
            model_name='heresearcharea',
            name='gtrs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='gtrs', to='rap.GTRCategory'),
        ),
    ]
