# Generated by Django 2.2.11 on 2020-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0002_auto_20200319_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='json',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
