# Generated by Django 2.2.11 on 2020-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0004_auto_20200319_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
