# Generated by Django 2.2.11 on 2020-03-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0005_auto_20200320_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtag',
            name='instance_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='socialtaginstance',
            name='socialtag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='rap.SocialTag'),
        ),
    ]
