# Generated by Django 2.2.11 on 2020-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0006_auto_20200320_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialtag',
            options={'ordering': ('-instance_count',), 'verbose_name': 'Calais Social Tag', 'verbose_name_plural': 'Social Tags'},
        ),
        migrations.AddField(
            model_name='entity',
            name='instance_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
