# Generated by Django 2.2.11 on 2020-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0007_auto_20200320_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='heresearcharea',
            name='entities',
            field=models.ManyToManyField(blank=True, default=None, related_name='entities', to='rap.GTRCategory'),
        ),
        migrations.AddField(
            model_name='heresearcharea',
            name='socialtags',
            field=models.ManyToManyField(blank=True, default=None, related_name='socialtags', to='rap.GTRCategory'),
        ),
    ]
