# Generated by Django 2.2.11 on 2020-03-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0008_auto_20200320_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heresearcharea',
            name='entities',
            field=models.ManyToManyField(blank=True, default=None, related_name='entities', to='rap.Entity'),
        ),
        migrations.AlterField(
            model_name='heresearcharea',
            name='socialtags',
            field=models.ManyToManyField(blank=True, default=None, related_name='socialtags', to='rap.SocialTag'),
        ),
    ]
